services:
  - type: web
    name: cyna-api
    runtime: docker
    plan: free
    region: frankfurt
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: Cyna API
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: MAIL_MAILER
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM_ADDRESS
        sync: false
      - key: MAIL_FROM_NAME
        value: Cyna API
      - key: STRIPE_KEY
        sync: false
      - key: STRIPE_SECRET
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: CASHIER_CURRENCY
        value: eur
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_FOLDER
        value: cyna

  - type: worker
    name: cyna-api-queue
    runtime: docker
    plan: free
    region: frankfurt
    dockerCommand: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    envVars:
      - key: APP_NAME
        value: Cyna API
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        fromService:
          type: web
          name: cyna-api
          envVarKey: APP_KEY
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: QUEUE_CONNECTION
        value: database
      - key: STRIPE_KEY
        sync: false
      - key: STRIPE_SECRET
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: CASHIER_CURRENCY
        value: eur
